import {
	FaAngular,
	FaBootstrap,
	FaCss3Alt,
	FaFigma,
	FaGithub,
	FaHtml5,
	FaJava,
	FaJsSquare,
	FaNodeJs,
	FaPhp,
	FaPython,
	FaReact,
	FaVuejs,
} from "react-icons/fa";

import {
	SiDjango,
	SiExpress,
	SiFirebase,
	SiFlutter,
	SiGooglecloud,
	SiMysql,
	SiNextdotjs,
	SiOpenai,
	SiSvelte,
	SiTailwindcss,
	SiTypescript,
	SiVite,
	SiGooglemaps,
} from "react-icons/si";

import { GiGemini } from "react-icons/gi";

export const AVAILABLE_TECHNOLOGIES = [
	{ name: "Angular", icon: FaAngular },
	{ name: "Bootstrap", icon: FaBootstrap },
	{ name: "CSS", icon: FaCss3Alt },
	{ name: "Django", icon: SiDjango },
	{ name: "Express", icon: SiExpress },
	{ name: "Figma", icon: FaFigma },
	{ name: "Firebase", icon: SiFirebase },
	{ name: "Flutter", icon: SiFlutter },
	{ name: "FlutterFlow", icon: SiFlutter },
	{ name: "Gemini", icon: GiGemini },
	{ name: "Git", icon: FaGithub },
	{ name: "GitHub", icon: FaGithub },
	{ name: "Google Maps", icon: SiGooglemaps },
	{ name: "HTML", icon: FaHtml5 },
	{ name: "Java", icon: FaJava },
	{ name: "JavaScript", icon: FaJsSquare },
	{ name: "MySQL", icon: SiMysql },
	{ name: "Next.js", icon: SiNextdotjs },
	{ name: "Node.js", icon: FaNodeJs },
	{ name: "OpenAI", icon: SiOpenai },
	{ name: "PHP", icon: FaPhp },
	{ name: "Python", icon: FaPython },
	{ name: "ReactJS", icon: FaReact },
	{ name: "REST API", icon: SiGooglecloud },
	{ name: "Svelte", icon: SiSvelte },
	{ name: "Tailwind CSS", icon: SiTailwindcss },
	{ name: "TypeScript", icon: SiTypescript },
	{ name: "Vite", icon: SiVite },
	{ name: "Vue.js", icon: FaVuejs },
];
